# Generated by Django 4.2.5 on 2024-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0009_checkinrecord_alter_timenumber_default_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorAffair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="医生名字")),
                ("leave", models.CharField(max_length=10, verbose_name="请假")),
                ("business", models.CharField(max_length=10, verbose_name="出差")),
                ("apply", models.CharField(max_length=10, verbose_name="报销")),
                ("solveleave", models.IntegerField(max_length=10, verbose_name="批准请假")),
                (
                    "solvebusiness",
                    models.IntegerField(max_length=10, verbose_name="批准出差"),
                ),
                ("solve", models.IntegerField(max_length=10, verbose_name="批准")),
            ],
            options={
                "verbose_name": "医生事务",
                "verbose_name_plural": "事务列表",
            },
        ),
    ]
