# Generated by Django 4.2.5 on 2024-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0010_doctoraffair"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoraffair",
            name="status",
            field=models.CharField(choices=[("a", "ratify")], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
